---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      github-actions:
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directories:
      - "/cloud_functions/runtask_callback"
      - "/cloud_functions/runtask_echo"
      - "/cloud_functions/runtask_process"
      - "/cloud_functions/runtask_request"
      - "/cloud_functions/tests"
      - "/tests"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      python:
        update-types: ["minor", "patch"]

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      terraform:
        update-types: ["minor", "patch"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      pre-commit:
        update-types: ["minor", "patch"]
